### ISSUE TITLE
Somethings need two CTRL-D to quit xcShell

### ISSUE THREAD

**Issue by superxcgm** [superxcgm/xcShell#25]
## Current Behavior
<img width="306" alt="image" src="https://user-images.githubusercontent.com/14891023/124336862-6f308d00-dbd2-11eb-94ff-164d613ccc90.png">

## Expected Behavior
Only hit CTRL-D once.

**Comment by superxcgm** [comment]
Cause: child process do not auto quit correctly when `exec` failed. So, first C-D send to child process, and the second C-D send to parent process.

**Comment by lq1149622825** [comment]
### Test against the expected result of ctrl+d
**Related test cases and results：**
#### case 1: 
when : user hit ctrl+d;
Then: the bash quit;
Result: True;
#### case 2:
when : user using command,like bc;
Then : bc program quit,bash did not quit;
Result: True , but no line break after exit; 
#### case 3: 
When : the user is executing an executable file, such as sleep 5 in the process
Then : the bash did not exist ,but if user hit Ctrl+d , bash exit after sleep
Result: true;
