### ISSUE TITLE
Single pipe `|`

### ISSUE THREAD

**Issue by superxcgm** [superxcgm/xcShell#42]
## Epic
[Process](https://github.com/superxcgm/xcShell/issues/2)

## Description
For good user experience, user can add chain commands using pipeline

## AC
Given: User type `some_command` (For example: echo ab)
When: User hit <Enter>
Then: Print ab on console.

Given: User type `some_command | another_command` (For example:`ls -l  | grep 'hello' `)
When: User hit <Enter>
Then: Should use output of first command as input of second command.

## Out of Scope
Support of multi pipe, like `command1 | command2 | command3`

**Comment by lq1149622825** [comment]
#### Technical knowledge used
1. fork() multi-process programming
2. pipe principle
3. Redirection principle
#### tsaking
1. Split the command to get the set of command_parse_result;
2. Get the set of command_pase_result, and get the part that needs "|" for processing according to the size
3. Create two child processes. Colleagues process two commands, and write the output of the first command to the pipeline at the same time, and the second line of commands is processed from the read data
4. refactor

**Comment by lq1149622825** [comment]
## 9月22日

**redirection bug**
- such as user input "> a.txt || < a.txt" ,  program error

**single Pipe line progress**
- Steps 1 to 3 are basically completed, there is a problem with pipeline redirection, which needs to be resolved（solved today）

**Comment by lq1149622825** [comment]
## 9月23日

**redirection bug**
- such as user input "> a.txt || < a.txt" ,  program error
- such as user input "alias" , program having nothing print

**single Pipe line progress**
- solve the build_in command pipe line(build_in alias have bug,such as user input "alias ll = 'ls -lh'",or input "alias",program have no output)

**mutil Pipe line progress**
- do the tasking with mutil pipe card;

**Comment by superxcgm** [comment]
# QA
Given: User type some_command (For example: echo ab)
When: User hit 
Then: ✅Print ab on console.

Given: User type some_command | another_command (For example:ls -l | grep 'hello' )
When: User hit 
Then: ✅Should use output of first command as input of second command.
