### ISSUE TITLE
Signal handle for CTRL + C (SIGINT)

### ISSUE THREAD

**Issue by superxcgm** [superxcgm/xcShell#44]
## Epic
[Process](https://github.com/superxcgm/xcShell/issues/2)

## Description
xcShell should not quit when user press `CTRL + C`(SIGINT), the program run by xcShell should handle `CTRL + C`(SIGINT) as normal.

## AC
Given: User in xcShell prompt
When: User hit <CTRL + C>
Then: No quit xcShell.

Given: User use xcShell to run some program, and program haven't quit yet. (For example: bc)
When: User hit <CTRL + C>
Then: Program should handle `CTRL + C` normally, while xcShell do not react anything.

**Comment by lq1149622825** [comment]
### Test against the expected result of ctrl+c
**Related test cases and results：**
#### case 1: 
when : user write nothing,hit ctrl+c;
Then: the bash should wrap;
Result: false;
#### case 2:
when : user using command, such as bc sleep;
Then : bc/sleep program quit;
Result: True , but no line break after exit;
