### ISSUE TITLE
Multi pipe `|`

### ISSUE THREAD

**Issue by superxcgm** [superxcgm/xcShell#53]
## Epic
[Process](https://github.com/superxcgm/xcShell/issues/2)

## Description
For good user experience, user can add chain commands using pipeline

## AC
**Given**: User type `command1 | command2 | command3` (For example: `cat /etc/passwd | grep sh | less`)
**When**: User hit `<Enter>`
**Then**: Output of first command should be input of second command, and output of second command should be input of third command.

**Comment by lq1149622825** [comment]
## 9月24日

**tasking：**
- 1.create n-1 pipes in a loop，Create n-1 pipes in a loop, write cmd1 to 1, cmd2 to read pipe1, cmd2 to write 2, and so on
- 2.logical refactoring
